#!/usr/bin/env bash
# Hey Laya — system installer (Linux).
# Creates venv if needed, installs deps, puts `hey-laya` on PATH, adds a
# desktop entry. Idempotent: safe to re-run.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
APP_DIR="$HOME/.local/share/applications"
PY="${PYTHON:-python3}"

echo "== Hey Laya installer =="

# --- sanity -----------------------------------------------------------------
command -v "$PY" >/dev/null || { echo "error: $PY not found"; exit 1; }
"$PY" - <<'EOF'
import sys
assert sys.version_info >= (3, 10), f"need Python ≥3.10, got {sys.version}"
print(f"python {sys.version.split()[0]} ok")
EOF

# --- venv -------------------------------------------------------------------
if [ ! -x "$ROOT/.venv/bin/python" ]; then
    echo "creating venv…"
    "$PY" -m venv "$ROOT/.venv"
fi
VENV="$ROOT/.venv/bin/python"

echo "installing deps (this can take a few minutes)…"
if command -v uv >/dev/null; then
    uv pip install --python "$VENV" --quiet -r "$ROOT/requirements.txt"
    uv pip install --python "$VENV" --quiet pyflakes   # for test_all.py lint step
else
    if ! "$VENV" -m pip --version >/dev/null 2>&1; then
        "$VENV" -m ensurepip --upgrade >/dev/null
    fi
    "$VENV" -m pip install --quiet --upgrade pip
    "$VENV" -m pip install --quiet -r "$ROOT/requirements.txt"
    "$VENV" -m pip install --quiet pyflakes   # for test_all.py lint step
fi

# --- config -----------------------------------------------------------------
if [ ! -f "$ROOT/.env" ]; then
    cp "$ROOT/.env.example" "$ROOT/.env"
    echo "wrote .env from .env.example — edit paths if needed"
fi

# --- launcher ---------------------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/hey-laya" <<EOF
#!/usr/bin/env bash
# Hey Laya launcher (generated by install.sh)
export PYTHONPATH="$ROOT\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$VENV" "$ROOT/main.py" "\$@"
EOF
chmod +x "$BIN_DIR/hey-laya"
echo "installed CLI → $BIN_DIR/hey-laya"

# --- desktop entry ----------------------------------------------------------
mkdir -p "$APP_DIR"
cat > "$APP_DIR/hey-laya.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Hey Laya
Comment=Local voice assistant (Laya decision layer)
Exec=$BIN_DIR/hey-laya
Terminal=false
Categories=AudioVideo;Utility;
Keywords=voice;assistant;laya;microphone;
EOF
chmod 644 "$APP_DIR/hey-laya.desktop"
command -v update-desktop-database >/dev/null && update-desktop-database "$APP_DIR" 2>/dev/null || true
echo "installed desktop entry → $APP_DIR/hey-laya.desktop"

# --- PATH hint ---------------------------------------------------------------
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "note: add $BIN_DIR to PATH (e.g. in ~/.bashrc: export PATH=\"\$HOME/.local/bin:\$PATH\")" ;;
esac

# --- smoke -------------------------------------------------------------------
echo "== smoke =="
"$BIN_DIR/hey-laya" --help >/dev/null && echo "hey-laya --help ok"
"$VENV" "$ROOT/test_all.py" | tail -2

echo "== done =="
echo "Run:  hey-laya                 # full voice mode (PTT + wake word)"
echo "      hey-laya --text \"volume up\""
echo "      hey-laya --fixture fixtures/routing.txt"
